server:
  port: ${PORT:8080}

api:
  prefix: /api/v1

spring:
  application:
    name: nocket
  output:
    ansi:
      enabled: ALWAYS
  messages:
    basename: i18n/messages
    encoding: UTF-8

  datasource:
    url: ${SPRING_DATASOURCE_URL:PROD_SPRING_DATASOURCE_URL}
    username: ${DB_DEV_USER:PROD_DB_DEV_USER}
    password: ${DB_DEV_PASSWORD:PROD_DB_DEV_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH2_CLIENT_ID}
            clientSecret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

  data:
    redis:
      #spring.data.redis.use-redis-cache
      use-redis-cache: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

alert:
  manager:
    emails: ${ALERT_MANAGER_EMAILS}

jwt:
  expiration: ${JWT_EXPIRATION}
  expiration-refresh-token: ${JWT_EXPIRATION_REFRESH_TOKEN}
  secretKey: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework: DEBUG
    springframework.security: DEBUG
    org.hibernate: DEBUG
  file:
    path: ${LOG_PATH:logs}
    name: ${LOG_PATH:logs}/application.log

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

#health check
management:
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

# 3rd party
unsplash:
  api:
    root: ${UNSPLASH_ROOT}
    client-id: ${UNSPLASH_CLIENT_ID}

vnpay:
  api:
    vnp_Version: ${VNPAY_VERSION}
    vnp_Command: ${VNPAY_COMMAND}
    vnp_OrderType: ${VNPAY_ORDER_TYPE}
    vnp_PayUrl: ${VNPAY_PAY_URL}
    vnp_Returnurl: ${VNPAY_RETURN_URL}
    vnp_TmnCode: ${VNPAY_TMN_CODE}
    vnp_HashSecret: ${VNPAY_HASH_SECRET}
    vnp_apiUrl: ${VNPAY_API_URL}
