global:
  scrape_interval: 5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'spring-boot-app-metrics'
    scrape_interval: 5s
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:4000']

rule_files:
  - alert.rules.yml  # Include your alert rules file here